name: Build Debian Package

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper

    - name: Build Debian package
      run: |
        cd debian  # 进入 debian 目录
        dpkg-buildpackage -us -uc

    - name: Upload .deb package
      uses: actions/upload-artifact@v2
      with:
        name: wapp
        path: ${{ github.workspace }}/wapp/
