name: Build and Package Qt Project as Debian Package

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: qmfrederik/setup-qt@v3
      with:
        qt-version: '5.15'  

    - name: Install required build tools and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper


    - name: Build Qt project
      run: |
        qmake  # 根据您的项目需要调整这个命令
        make


    - name: Create Debian package directory
      run: |
        mkdir -p debian/package
        cp -R path/to/your/built/executable debian/package/  # 将生成的可执行文件复制到包目录
        # 如果有其他文件或配置文件需要包含，也请复制到相应的位置

    - name: Package the Qt project
      run: |
        dpkg-deb --build debian debian-package.deb

    - name: Upload Debian package
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: debian-package.deb
