name: Build and Package Qt Project as Debian Package

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: qmfrederik/setup-qt@v3
      with:
        qt-version: '5.15'  

    - name: Install required build tools and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper


    - name: Build Qt project
      run: |
        qmake  
        make


    - name: Create Debian package directory
      run: |
        mkdir -p debian/package
        cp -R path/to/your/built/executable debian/package/  

    - name: Package the Qt project
      run: |
        dpkg-deb --build wapp wapp_linux_arm64.deb

    - name: Upload Debian package
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: debian-package.deb
